services:
  backend:
    image: emfall/deploiement-backend:latest
    container_name: deploiement-backend
    ports:
      - "3000:3000"
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    image: emfall/deploiement-frontend:latest
    container_name: deploiement-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
