# Nom du workflow affiché dans GitHub Actions
name: CI

# Définit quand la CI doit être déclenchée
on:

  # La CI se lance lorsqu'on fait un push
  push:
    branches:
      # Sur la branche principale
      - main

      # Et sur la branche de développement
      - develop

  # La CI se lance également lorsqu'on crée/modifie une Pull Request
  pull_request:
    branches:
      # Pull Request vers main
      - main

      # Pull Request vers develop
      - develop


# Définition des tâches de la CI
jobs:

  # Nom de notre tâche
  build:

    # Machine virtuelle utilisée par GitHub pour exécuter la CI
    runs-on: ubuntu-latest

    # Liste des étapes exécutées dans l'ordre
    steps:

      # Récupère le code de notre dépôt GitHub
      - name: Récupérer le code
        uses: actions/checkout@v4


      # Vérifie que Docker est disponible
      - name: Vérifier Docker
        run: docker --version


      # Vérifie que Docker Compose est disponible
      - name: Vérifier Docker Compose
        run: docker compose version


      # Construit les images Docker du frontend et du backend
      # en utilisant le docker-compose.yml
      - name: Construire les images
        run: docker compose build


      # Démarre les conteneurs en arrière-plan
      - name: Démarrer les services
        run: docker compose up -d


      # Affiche l'état des conteneurs
      # Permet de vérifier qu'ils sont bien démarrés
      - name: Vérifier les conteneurs
        run: docker compose ps


      # Arrête et supprime les conteneurs
      # Cette étape permet de nettoyer la machine après les tests
      - name: Arrêter les services
        run: docker compose down